//Vial and Crack Detection Algoryhtm - Group 464 ROB4
//V6.0 - 20/05/2020

#include <iostream>
#include <opencv2/core.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/imgcodecs.hpp>
#include <vector>
#include <math.h>
#include <cmath>
#include "Vials.h"

using namespace cv;
using namespace std;

cv::Mat test1 = cv::imread("C:\\Users\\artur\\Desktop\\Test\\9_2.png");
cv::Mat test2 = cv::imread("C:\\Users\\artur\\Desktop\\Test\\41_Color.png");
cv::Mat test3 = cv::imread("C:\\Users\\artur\\Desktop\\Test\\113_Color.png");
cv::Mat test4 = cv::imread("C:\\Users\\artur\\Desktop\\Test\\149_Color.png");
cv::Mat test5 = cv::imread("C:\\Users\\artur\\Desktop\\Test\\163_Color.png");
cv::Mat test6 = cv::imread("C:\\Users\\artur\\Desktop\\Test\\4_Color.png");
cv::Mat test7 = cv::imread("C:\\Users\\artur\\Desktop\\Test\\24_Color.png");
cv::Mat test8 = cv::imread("C:\\Users\\artur\\Desktop\\Test\\46_Color.png");
cv::Mat test9 = cv::imread("C:\\Users\\artur\\Desktop\\Test\\134_Color.png");

//TestData//HarmedTestData
//Vial 1 
cv::Mat vial1_1 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\1_Color.png");
cv::Mat vial1_2 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\2_Color.png");
cv::Mat vial1_3 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\3_Color.png");
cv::Mat vial1_4 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\4_Color.png");
//Vial 2
cv::Mat vial2_1 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\5_Color.png");
cv::Mat vial2_2 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\6_Color.png");
cv::Mat vial2_3 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\7_Color.png");
cv::Mat vial2_4 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\8_Color.png");
//Vial 3
cv::Mat vial3_1 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\9_Color.png");
cv::Mat vial3_2 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\10_Color.png");
cv::Mat vial3_3 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\11_Color.png");
cv::Mat vial3_4 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\12_Color.png");
//Vial 4
cv::Mat vial4_1 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\13_Color.png");
cv::Mat vial4_2 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\14_Color.png");
cv::Mat vial4_3 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\15_Color.png");
cv::Mat vial4_4 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\16_Color.png");
//Vial 5
cv::Mat vial5_1 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\17_Color.png");
cv::Mat vial5_2 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\18_Color.png");
cv::Mat vial5_3 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\19_Color.png");
cv::Mat vial5_4 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\20_Color.png");
//Vial 6
cv::Mat vial6_1 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\21_Color.png");
cv::Mat vial6_2 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\22_Color.png");
cv::Mat vial6_3 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\23_Color.png");
cv::Mat vial6_4 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\24_Color.png");
//Vial 7
cv::Mat vial7_1 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\25_Color.png");
cv::Mat vial7_2 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\26_Color.png");
cv::Mat vial7_3 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\27_Color.png");
cv::Mat vial7_4 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\28_Color.png");
//Vial 8
cv::Mat vial8_1 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\29_Color.png");
cv::Mat vial8_2 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\30_Color.png");
cv::Mat vial8_3 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\31_Color.png");
cv::Mat vial8_4 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\32_Color.png");
//Vial 9
cv::Mat vial9_1 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\33_Color.png");
cv::Mat vial9_2 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\34_Color.png");
cv::Mat vial9_3 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\35_Color.png");
cv::Mat vial9_4 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\36_Color.png");
//Vial 10
cv::Mat vial10_1 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\37_Color.png");
cv::Mat vial10_2 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\38_Color.png");
cv::Mat vial10_3 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\39_Color.png");
cv::Mat vial10_4 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\40_Color.png");
//Vial 11
cv::Mat vial11_1 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\41_Color.png");
cv::Mat vial11_2 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\42_Color.png");
cv::Mat vial11_3 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\43_Color.png");
cv::Mat vial11_4 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\44_Color.png");
//Vial 12
cv::Mat vial12_1 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\45_Color.png");
cv::Mat vial12_2 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\46_Color.png");
cv::Mat vial12_3 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\47_Color.png");
cv::Mat vial12_4 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\48_Color.png");
//Vial 13
cv::Mat vial13_1 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\49_Color.png");
cv::Mat vial13_2 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\50_Color.png");
cv::Mat vial13_3 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\51_Color.png");
cv::Mat vial13_4 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\52_Color.png");
//Vial 14
cv::Mat vial14_1 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\53_Color.png");
cv::Mat vial14_2 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\54_Color.png");
cv::Mat vial14_3 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\55_Color.png");
cv::Mat vial14_4 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\56_Color.png");
//Vial 15
cv::Mat vial15_1 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\57_Color.png");
cv::Mat vial15_2 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\58_Color.png");
cv::Mat vial15_3 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\59_Color.png");
cv::Mat vial15_4 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\60_Color.png");
//Vial 16
cv::Mat vial16_1 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\61_Color.png");
cv::Mat vial16_2 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\62_Color.png");
cv::Mat vial16_3 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\63_Color.png");
cv::Mat vial16_4 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\64_Color.png");
//Vial 17
cv::Mat vial17_1 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\65_Color.png");
cv::Mat vial17_2 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\66_Color.png");
cv::Mat vial17_3 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\67_Color.png");
cv::Mat vial17_4 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\68_Color.png");
//Vial 18
cv::Mat vial18_1 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\69_Color.png");
cv::Mat vial18_2 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\70_Color.png");
cv::Mat vial18_3 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\71_Color.png");
cv::Mat vial18_4 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\72_Color.png");
//Vial 19
cv::Mat vial19_1 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\73_Color.png");
cv::Mat vial19_2 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\74_Color.png");
cv::Mat vial19_3 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\75_Color.png");
cv::Mat vial19_4 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\HarmedTestData\\76_Color.png");

//TestData//GoodTestData
cv::Mat goodtest1 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\1_Color.png");
cv::Mat goodtest2 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\2_Color.png");
cv::Mat goodtest3 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\3_Color.png");
cv::Mat goodtest4 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\4_Color.png");
cv::Mat goodtest5 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\5_Color.png");
cv::Mat goodtest6 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\6_Color.png");
cv::Mat goodtest7 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\7_Color.png");
cv::Mat goodtest8 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\8_Color.png");
cv::Mat goodtest9 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\9_Color.png");
cv::Mat goodtest10 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\10_Color.png");
cv::Mat goodtest11 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\11_Color.png");
cv::Mat goodtest12 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\12_Color.png");
cv::Mat goodtest13 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\13_Color.png");
cv::Mat goodtest14 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\14_Color.png");
cv::Mat goodtest15 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\15_Color.png");
cv::Mat goodtest16 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\16_Color.png");
cv::Mat goodtest17 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\17_Color.png");
cv::Mat goodtest18 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\18_Color.png");
cv::Mat goodtest19 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\19_Color.png");
cv::Mat goodtest20 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\20_Color.png");
cv::Mat goodtest21 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\21_Color.png");
cv::Mat goodtest22 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\22_Color.png");
cv::Mat goodtest23 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\23_Color.png");
cv::Mat goodtest24 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\24_Color.png");
cv::Mat goodtest25 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\25_Color.png");
cv::Mat goodtest26 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\26_Color.png");
cv::Mat goodtest27 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\27_Color.png");
cv::Mat goodtest28 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\28_Color.png");
cv::Mat goodtest29 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\29_Color.png");
cv::Mat goodtest30 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\30_Color.png");
cv::Mat goodtest31 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\31_Color.png");
cv::Mat goodtest32 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\32_Color.png");
cv::Mat goodtest33 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\33_Color.png");
cv::Mat goodtest34 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\34_Color.png");
cv::Mat goodtest35 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\35_Color.png");
cv::Mat goodtest36 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\36_Color.png");
cv::Mat goodtest37 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\37_Color.png");
cv::Mat goodtest38 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\38_Color.png");
cv::Mat goodtest39 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\39_Color.png");
cv::Mat goodtest40 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\40_Color.png");
cv::Mat goodtest41 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\41_Color.png");
cv::Mat goodtest42 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\42_Color.png");
cv::Mat goodtest43 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\43_Color.png");
cv::Mat goodtest44 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\44_Color.png");
cv::Mat goodtest45 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\45_Color.png");
cv::Mat goodtest46 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\46_Color.png");
cv::Mat goodtest47 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\47_Color.png");
cv::Mat goodtest48 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\48_Color.png");
cv::Mat goodtest49 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\49_Color.png");
cv::Mat goodtest50 = cv::imread("C:\\Users\\artur\\Desktop\\TestData\\GoodTestData\\50_Color.png");


void main()
{
	inspectVial data;
	data.loadDataTop();
	data.loadDataBottom();
	data.loadDataCrack();
	data.loadDataScratch();
	
	//TrainingData//Good
	/*
	cout << "good1" << endl;
	data.alldata(data.good1);
	cout << "good2" << endl;
	data.alldata(data.good2);
	cout << "good3" << endl;
	data.alldata(data.good3);
	cout << "good4" << endl;
	data.alldata(data.good4);
	cout << "good5" << endl;
	data.alldata(data.good5);
	cout << "good6" << endl;
	data.alldata(data.good6);
	cout << "good7" << endl;
	data.alldata(data.good7);
	cout << "good8" << endl;
	data.alldata(data.good8);
	cout << "good9" << endl;
	data.alldata(data.good9);
	cout << "good10" << endl;
	data.alldata(data.good10);
	cout << "good11" << endl;
	data.alldata(data.good11);
	cout << "good12" << endl;
	data.alldata(data.good12);
	cout << "good13" << endl;
	data.alldata(data.good13);
	cout << "good14" << endl;
	data.alldata(data.good14);
	cout << "good15" << endl;
	data.alldata(data.good15);
	cout << "good16" << endl;
	data.alldata(data.good16);
	cout << "good17" << endl;
	data.alldata(data.good17);
	cout << "good18" << endl;
	data.alldata(data.good18);
	cout << "good19" << endl;
	data.alldata(data.good19);
	cout << "good20" << endl;
	data.alldata(data.good20);
	cout << "good21" << endl;
	data.alldata(data.good21);
	cout << "good22" << endl;
	data.alldata(data.good22);
	cout << "good23" << endl;
	data.alldata(data.good23);
	cout << "good24" << endl;
	data.alldata(data.good24);
	cout << "good25" << endl;
	data.alldata(data.good25);
	cout << "good26" << endl;
	data.alldata(data.good26);
	cout << "good27" << endl;
	data.alldata(data.good27);
	cout << "good28" << endl;
	data.alldata(data.good28);
	cout << "good29" << endl;
	data.alldata(data.good29);
	cout << "good30" << endl;
	data.alldata(data.good30);
	*/
	
	//TrainingData//Mixed
	/*
	cout << "Vial 1" << endl;
	data.alldata(data.vial1);
	cout << "Vial 2" << endl;
	data.alldata(data.vial2);
	cout << "Vial 3" << endl;
	data.alldata(data.vial3);
	cout << "Vial 4" << endl;
	data.alldata(data.vial4);
	cout << "Vial 5" << endl;
	data.alldata(data.vial5);
	cout << "Vial 6" << endl;
	data.alldata(data.vial6);
	cout << "Vial 7" << endl;
	data.alldata(data.vial7);
	cout << "Vial 8" << endl;
	data.alldata(data.vial8);
	cout << "Vial 9" << endl;
	data.alldata(data.vial9);
	cout << "Vial 10" << endl;
	data.alldata(data.vial10);
	cout << "Vial 11" << endl;
	data.alldata(data.vial11);
	cout << "Vial 12" << endl;
	data.alldata(data.vial12);
	cout << "Vial 13" << endl;
	data.alldata(data.vial13);
	cout << "Vial 14" << endl;
	data.alldata(data.vial14);
	cout << "Vial 15" << endl;
	data.alldata(data.vial15);
	cout << "Vial 16" << endl;
	data.alldata(data.vial16);
	cout << "Vial 17" << endl;
	data.alldata(data.vial17);
	cout << "Vial 18" << endl;
	data.alldata(data.vial18);
	cout << "Vial 19" << endl;
	data.alldata(data.vial19);
	cout << "Vial 20" << endl;
	data.alldata(data.vial20);
	cout << "Vial 21" << endl;
	data.alldata(data.vial21);
	cout << "Vial 22" << endl;
	data.alldata(data.vial22);
	cout << "Vial 23" << endl;
	data.alldata(data.vial23);
	cout << "Vial 24" << endl;
	data.alldata(data.vial24);
	cout << "Vial 25" << endl;
	data.alldata(data.vial25);
	cout << "Vial 26" << endl;
	data.alldata(data.vial26);
	cout << "Vial 29" << endl;
	data.alldata(data.vial29);
	cout << "Vial 31" << endl;
	data.alldata(data.vial31);
	cout << "Vial 32" << endl;
	data.alldata(data.vial32);
	cout << "Vial 33" << endl;
	data.alldata(data.vial33);
	cout << "Vial 34" << endl;
	data.alldata(data.vial34);
	cout << "Vial 35" << endl;
	data.alldata(data.vial35);
	cout << "Vial 36" << endl;
	data.alldata(data.vial36);
	cout << "Vial 37" << endl;
	data.alldata(data.vial37);
	cout << "Vial 38" << endl;
	data.alldata(data.vial38);
	cout << "Vial 39" << endl;
	data.alldata(data.vial39);
	cout << "Vial 40" << endl;
	data.alldata(data.vial40);
	cout << "Vial 41" << endl;
	data.alldata(data.vial41);
	cout << "Vial 42" << endl;
	data.alldata(data.vial42);
	cout << "Vial 43" << endl;
	data.alldata(data.vial43);
	cout << "Vial 44" << endl;
	data.alldata(data.vial44);
	cout << "Vial 46" << endl;
	data.alldata(data.vial46);
	cout << "Vial 47" << endl;
	data.alldata(data.vial47);
	cout << "Vial 48" << endl;
	data.alldata(data.vial48);
	cout << "Vial 49" << endl;
	data.alldata(data.vial49);
	cout << "Vial 50" << endl;
	data.alldata(data.vial50);
	cout << "Vial 51" << endl;
	data.alldata(data.vial51);
	cout << "Vial 52" << endl;
	data.alldata(data.vial52);
	cout << "Vial 53" << endl;
	data.alldata(data.vial53);
	cout << "Vial 54" << endl;
	data.alldata(data.vial54);
	cout << "Vial 55" << endl;
	data.alldata(data.vial55);
	cout << "Vial 56" << endl;
	data.alldata(data.vial56);
	cout << "Vial 57" << endl;
	data.alldata(data.vial57);
	cout << "Vial 58" << endl;
	data.alldata(data.vial58);
	cout << "Vial 59" << endl;
	data.alldata(data.vial59);
	cout << "Vial 60" << endl;
	data.alldata(data.vial60);
	cout << "Vial 61" << endl;
	data.alldata(data.vial61);
	cout << "Vial 62" << endl;
	data.alldata(data.vial62);
	cout << "Vial 63" << endl;
	data.alldata(data.vial63);
	cout << "Vial 64" << endl;
	data.alldata(data.vial64);
	cout << "Vial 65" << endl;
	data.alldata(data.vial65);
	cout << "Vial 66" << endl;
	data.alldata(data.vial66);
	cout << "Vial 67" << endl;
	data.alldata(data.vial67);
	cout << "Vial 68" << endl;
	data.alldata(data.vial68);
	cout << "Vial 69" << endl;
	data.alldata(data.vial69);
	cout << "Vial 70" << endl;
	data.alldata(data.vial70);
	cout << "Vial 71" << endl;
	data.alldata(data.vial71);
	cout << "Vial 72" << endl;
	data.alldata(data.vial72);
	cout << "Vial 73" << endl;
	data.alldata(data.vial73);
	cout << "Vial 74" << endl;
	data.alldata(data.vial74);
	cout << "Vial 75" << endl;
	data.alldata(data.vial75);
	cout << "Vial 76" << endl;
	data.alldata(data.vial76);
	cout << "Vial 77" << endl;
	data.alldata(data.vial77);
	cout << "Vial 78" << endl;
	data.alldata(data.vial78);
	cout << "Vial 79" << endl;
	data.alldata(data.vial79);
	cout << "Vial 80" << endl;
	data.alldata(data.vial80);
	cout << "Vial 81" << endl;
	data.alldata(data.vial81);
	cout << "Vial 82" << endl;
	data.alldata(data.vial82);
	cout << "Vial 83" << endl;
	data.alldata(data.vial83);
	cout << "Vial 84" << endl;
	data.alldata(data.vial84);
	cout << "Vial 85" << endl;
	data.alldata(data.vial85);
	cout << "Vial 86" << endl;
	data.alldata(data.vial86);
	cout << "Vial 87" << endl;
	data.alldata(data.vial87);
	cout << "Vial 88" << endl;
	data.alldata(data.vial88);
	cout << "Vial 89" << endl;
	data.alldata(data.vial89);
	cout << "Vial 90" << endl;
	data.alldata(data.vial90);
	cout << "Vial 91" << endl;
	data.alldata(data.vial91);
	cout << "Vial 92" << endl;
	data.alldata(data.vial92);
	cout << "Vial 93" << endl;
	data.alldata(data.vial93);
	cout << "Vial 94" << endl;
	data.alldata(data.vial94);
	cout << "Vial 95" << endl;
	data.alldata(data.vial95);
	cout << "Vial 96" << endl;
	data.alldata(data.vial96);
	cout << "Vial 97" << endl;
	data.alldata(data.vial97);
	cout << "Vial 98" << endl;
	data.alldata(data.vial98);
	cout << "Vial 99" << endl;
	data.alldata(data.vial99);
	cout << "Vial 100" << endl;
	data.alldata(data.vial100);
	cout << "Vial 101" << endl;
	data.alldata(data.vial101);
	cout << "Vial 102" << endl;
	data.alldata(data.vial102);
	cout << "Vial 103" << endl;
	data.alldata(data.vial103);
	cout << "Vial 104" << endl;
	data.alldata(data.vial104);
	cout << "Vial 105" << endl;
	data.alldata(data.vial105);
	cout << "Vial 106" << endl;
	data.alldata(data.vial106);
	cout << "Vial 107" << endl;
	data.alldata(data.vial107);
	cout << "Vial 108" << endl;
	data.alldata(data.vial108);
	cout << "Vial 109" << endl;
	data.alldata(data.vial109);
	cout << "Vial 110" << endl;
	data.alldata(data.vial110);
	cout << "Vial 111" << endl;
	data.alldata(data.vial111);
	cout << "Vial 112" << endl;
	data.alldata(data.vial112);
	cout << "Vial 113" << endl;
	data.alldata(data.vial113);
	cout << "Vial 114" << endl;
	data.alldata(data.vial114);
	cout << "Vial 115" << endl;
	data.alldata(data.vial115);
	cout << "Vial 116" << endl;
	data.alldata(data.vial116);
	cout << "Vial 117" << endl;
	data.alldata(data.vial117);
	cout << "Vial 118" << endl;
	data.alldata(data.vial118);
	cout << "Vial 119" << endl;
	data.alldata(data.vial119);
	cout << "Vial 120" << endl;
	data.alldata(data.vial120);
	cout << "Vial 121" << endl;
	data.alldata(data.vial121);
	cout << "Vial 122" << endl;
	data.alldata(data.vial122);
	cout << "Vial 123" << endl;
	data.alldata(data.vial123);
	cout << "Vial 124" << endl;
	data.alldata(data.vial124);
	cout << "Vial 125" << endl;
	data.alldata(data.vial125);
	cout << "Vial 126" << endl;
	data.alldata(data.vial126);
	cout << "Vial 127" << endl;
	data.alldata(data.vial127);
	cout << "Vial 128" << endl;
	data.alldata(data.vial128);
	cout << "Vial 129" << endl;
	data.alldata(data.vial129);
	cout << "Vial 130" << endl;
	data.alldata(data.vial130);
	cout << "Vial 131" << endl;
	data.alldata(data.vial131);
	cout << "Vial 132" << endl;
	data.alldata(data.vial132);
	cout << "Vial 133" << endl;
	data.alldata(data.vial133);
	cout << "Vial 134" << endl;
	data.alldata(data.vial134);
	cout << "Vial 135" << endl;
	data.alldata(data.vial135);
	cout << "Vial 136" << endl;
	data.alldata(data.vial136);
	cout << "Vial 137" << endl;
	data.alldata(data.vial137);
	cout << "Vial 138" << endl;
	data.alldata(data.vial138);
	cout << "Vial 139" << endl;
	data.alldata(data.vial139);
	cout << "Vial 140" << endl;
	data.alldata(data.vial140);
	cout << "Vial 141" << endl;
	data.alldata(data.vial141);
	cout << "Vial 142" << endl;
	data.alldata(data.vial142);
	cout << "Vial 143" << endl;
	data.alldata(data.vial143);
	cout << "Vial 144" << endl;
	data.alldata(data.vial144);
	cout << "Vial 145" << endl;
	data.alldata(data.vial145);
	cout << "Vial 146" << endl;
	data.alldata(data.vial146);
	cout << "Vial 147" << endl;
	data.alldata(data.vial147);
	cout << "Vial 148" << endl;
	data.alldata(data.vial148);
	cout << "Vial 149" << endl;
	data.alldata(data.vial149);
	cout << "Vial 150" << endl;
	data.alldata(data.vial150);
	cout << "Vial 151" << endl;
	data.alldata(data.vial151);
	cout << "Vial 152" << endl;
	data.alldata(data.vial152);
	cout << "Vial 153" << endl;
	data.alldata(data.vial153);
	cout << "Vial 154" << endl;
	data.alldata(data.vial154);
	cout << "Vial 155" << endl;
	data.alldata(data.vial155);
	cout << "Vial 156" << endl;
	data.alldata(data.vial156);
	cout << "Vial 157" << endl;
	data.alldata(data.vial157);
	cout << "Vial 158" << endl;
	data.alldata(data.vial158);
	cout << "Vial 159" << endl;
	data.alldata(data.vial159);
	cout << "Vial 160" << endl;
	data.alldata(data.vial160);
	cout << "Vial 161" << endl;
	data.alldata(data.vial161);
	cout << "Vial 162" << endl;
	data.alldata(data.vial162);
	cout << "Vial 163" << endl;
	data.alldata(data.vial163);
	cout << "Vial 164" << endl;
	data.alldata(data.vial164);
	cout << "Vial 165" << endl;
	data.alldata(data.vial165);
	cout << "Vial 166" << endl;
	data.alldata(data.vial166);
	cout << "Vial 167" << endl;
	data.alldata(data.vial167);
	cout << "Vial 168" << endl;
	data.alldata(data.vial168);
	cout << "Vial 169" << endl;
	data.alldata(data.vial169);
	cout << "Vial 170" << endl;
	data.alldata(data.vial170);
	cout << "Vial 171" << endl;
	data.alldata(data.vial171);
	cout << "Vial 172" << endl;
	data.alldata(data.vial172);
	cout << "Vial 173" << endl;
	data.alldata(data.vial173);
	cout << "Vial 174" << endl;
	data.alldata(data.vial174);
	cout << "Vial 175" << endl;
	data.alldata(data.vial175);
	cout << "Vial 176" << endl;
	data.alldata(data.vial176);
	cout << "Vial 177" << endl;
	data.alldata(data.vial177);
	cout << "Vial 178" << endl;
	data.alldata(data.vial178);
	cout << "Vial 179" << endl;
	data.alldata(data.vial179);
	cout << "Vial 180" << endl;
	data.alldata(data.vial180);
	cout << "Vial 181" << endl;
	data.alldata(data.vial181);
	cout << "Vial 182" << endl;
	data.alldata(data.vial182);
	cout << "Vial 183" << endl;
	data.alldata(data.vial183);
	cout << "Vial 184" << endl;
	data.alldata(data.vial184);
	cout << "Vial 185" << endl;
	data.alldata(data.vial185);
	cout << "Vial 186" << endl;
	data.alldata(data.vial186);
	cout << "Vial 187" << endl;
	data.alldata(data.vial187);
	cout << "Vial 188" << endl;
	data.alldata(data.vial188);
	cout << "Vial 189" << endl;
	data.alldata(data.vial189);
	cout << "Vial 190" << endl;
	data.alldata(data.vial190);
	cout << "Vial 191" << endl;
	data.alldata(data.vial191);
	cout << "Vial 192" << endl;
	data.alldata(data.vial192);
	cout << "Vial 193" << endl;
	data.alldata(data.vial193);
	cout << "Vial 194" << endl;
	data.alldata(data.vial194);
	cout << "Vial 195" << endl;
	data.alldata(data.vial195);
	cout << "Vial 196" << endl;
	data.alldata(data.vial196);
	cout << "Vial 197" << endl;
	data.alldata(data.vial197);
	cout << "Vial 198" << endl;
	data.alldata(data.vial198);
	cout << "Vial 199" << endl;
	data.alldata(data.vial199);
	cout << "Vial 200" << endl;
	data.alldata(data.vial200);
	cout << "Vial 201" << endl;
	data.alldata(data.vial201);
	cout << "Vial 202" << endl;
	data.alldata(data.vial202);
	cout << "Vial 203" << endl;
	data.alldata(data.vial203);
	cout << "Vial 204" << endl;
	data.alldata(data.vial204);
	cout << "Vial 205" << endl;
	data.alldata(data.vial205);
	cout << "Vial 206" << endl;
	data.alldata(data.vial206);
	cout << "Vial 207" << endl;
	data.alldata(data.vial207);
	cout << "Vial 208" << endl;
	data.alldata(data.vial208);
	cout << "Vial 209" << endl;
	data.alldata(data.vial209);
	cout << "Vial 210" << endl;
	data.alldata(data.vial210);
	cout << "Vial 211" << endl;
	data.alldata(data.vial211);
	cout << "Vial 212" << endl;
	data.alldata(data.vial212);
	*/

	//TrainingData//Scratches
	/*
	cout << "scratch 1" << endl;
	data.alldata(data.scratch1);
	cout << "scratch 2" << endl;
	data.alldata(data.scratch2);
	cout << "scratch 3" << endl;
	data.alldata(data.scratch3);
	cout << "scratch 4" << endl;
	data.alldata(data.scratch4);
	cout << "scratch 5" << endl;
	data.alldata(data.scratch5);
	cout << "scratch 6" << endl;
	data.alldata(data.scratch6);
	cout << "scratch 7" << endl;
	data.alldata(data.scratch7);
	cout << "scratch 8" << endl;
	data.alldata(data.scratch8);
	cout << "scratch 9" << endl;
	data.alldata(data.scratch9);
	//cout << "scratch 10" << endl;
	//data.alldata(data.scratch10);
	//cout << "scratch 11" << endl;
	//data.alldata(data.scratch11);
	//cout << "scratch 12" << endl;
	//data.alldata(data.scratch12);
	//cout << "scratch 13" << endl;
	//data.alldata(data.scratch13);
	//cout << "scratch 14" << endl;
	//data.alldata(data.scratch14);
	//cout << "scratch 15" << endl;
	//data.alldata(data.scratch15);
	//cout << "scratch 16" << endl;
	//data.alldata(data.scratch16);
	//cout << "scratch 17" << endl;
	//data.alldata(data.scratch17);
	//cout << "scratch 18" << endl;
	//data.alldata(data.scratch18);
	cout << "scratch 19" << endl;
	data.alldata(data.scratch19);
	cout << "scratch 20" << endl;
	data.alldata(data.scratch20);
	cout << "scratch 21" << endl;
	data.alldata(data.scratch21);
	cout << "scratch 22" << endl;
	data.alldata(data.scratch22);
	cout << "scratch 23" << endl;
	data.alldata(data.scratch23);
	cout << "scratch 24" << endl;
	data.alldata(data.scratch24);
	cout << "scratch 25" << endl;
	data.alldata(data.scratch25);
	cout << "scratch 26" << endl;
	data.alldata(data.scratch26);
	cout << "scratch 29" << endl;
	data.alldata(data.scratch29);
	cout << "scratch 31" << endl;
	data.alldata(data.scratch31);
	cout << "scratch 32" << endl;
	data.alldata(data.scratch32);
	//cout << "scratch 33" << endl;
	//data.alldata(data.scratch33);
	//cout << "scratch 34" << endl;
	//data.alldata(data.scratch34);
	//cout << "scratch 35" << endl;
	//data.alldata(data.scratch35);
	//cout << "scratch 36" << endl;
	//data.alldata(data.scratch36);
	//cout << "scratch 37" << endl;
	//data.alldata(data.scratch37);
	cout << "scratch 38" << endl;
	data.alldata(data.scratch38);
	cout << "scratch 39" << endl;
	data.alldata(data.scratch39);
	//cout << "scratch 40" << endl;
	//data.alldata(data.scratch40);
	//cout << "scratch 41" << endl;
	//data.alldata(data.scratch41);
	//cout << "scratch 42" << endl;
	//data.alldata(data.scratch42);
	//cout << "scratch 43" << endl;
	//data.alldata(data.scratch43);
	cout << "scratch 44" << endl;
	data.alldata(data.scratch44);
	cout << "scratch 46" << endl;
	data.alldata(data.scratch46);
	cout << "scratch 47" << endl;
	data.alldata(data.scratch47);
	cout << "scratch 48" << endl;
	data.alldata(data.scratch48);
	cout << "scratch 49" << endl;
	data.alldata(data.scratch49);
	cout << "scratch 50" << endl;
	data.alldata(data.scratch50);
	cout << "scratch 51" << endl;
	data.alldata(data.scratch51);
	cout << "scratch 52" << endl;
	data.alldata(data.scratch52);
	cout << "scratch 53" << endl;
	data.alldata(data.scratch53);
	cout << "scratch 54" << endl;
	data.alldata(data.scratch54);
	cout << "scratch 55" << endl;
	data.alldata(data.scratch55);
	cout << "scratch 56" << endl;
	data.alldata(data.scratch56);
	cout << "scratch 57" << endl;
	data.alldata(data.scratch57);
	cout << "scratch 58" << endl;
	data.alldata(data.scratch58);
	cout << "scratch 59" << endl;
	data.alldata(data.scratch59);
	cout << "scratch 60" << endl;
	data.alldata(data.scratch60);
	cout << "scratch 61" << endl;
	data.alldata(data.scratch61);
	cout << "scratch 62" << endl;
	data.alldata(data.scratch62);
	cout << "scratch 63" << endl;
	data.alldata(data.scratch63);
	cout << "scratch 64" << endl;
	data.alldata(data.scratch64);
	cout << "scratch 65" << endl;
	data.alldata(data.scratch65);
	cout << "scratch 66" << endl;
	data.alldata(data.scratch66);
	cout << "scratch 67" << endl;
	data.alldata(data.scratch67);
	cout << "scratch 68" << endl;
	data.alldata(data.scratch68);
	cout << "scratch 69" << endl;
	data.alldata(data.scratch69);
	cout << "scratch 70" << endl;
	data.alldata(data.scratch70);
	cout << "scratch 71" << endl;
	data.alldata(data.scratch71);
	cout << "scratch 72" << endl;
	data.alldata(data.scratch72);
	cout << "scratch 73" << endl;
	data.alldata(data.scratch73);
	cout << "scratch 74" << endl;
	data.alldata(data.scratch74);
	cout << "scratch 75" << endl;
	data.alldata(data.scratch75);
	cout << "scratch 76" << endl;
	data.alldata(data.scratch76);
	cout << "scratch 77" << endl;
	data.alldata(data.scratch77);
	cout << "scratch 78" << endl;
	data.alldata(data.scratch78);
	cout << "scratch 79" << endl;
	data.alldata(data.scratch79);
	cout << "scratch 80" << endl;
	data.alldata(data.scratch80);
	//cout << "scratch 81" << endl;
	//data.alldata(data.scratch81);
	//cout << "scratch 82" << endl;
	//data.alldata(data.scratch82);
	cout << "scratch 83" << endl;
	data.alldata(data.scratch83);
	cout << "scratch 84" << endl;
	data.alldata(data.scratch84);
	//cout << "scratch 85" << endl;
	//data.alldata(data.scratch85);
	cout << "scratch 86" << endl;
	data.alldata(data.scratch86);
	cout << "scratch 87" << endl;
	data.alldata(data.scratch87);
	cout << "scratch 88" << endl;
	data.alldata(data.scratch88);
	cout << "scratch 89" << endl;
	data.alldata(data.scratch89);
	cout << "scratch 90" << endl;
	data.alldata(data.scratch90);
	cout << "scratch 91" << endl;
	data.alldata(data.scratch91);
	cout << "scratch 92" << endl;
	data.alldata(data.scratch92);
	cout << "scratch 93" << endl;
	data.alldata(data.scratch93);
	cout << "scratch 94" << endl;
	data.alldata(data.scratch94);
	cout << "scratch 95" << endl;
	data.alldata(data.scratch95);
	cout << "scratch 96" << endl;
	data.alldata(data.scratch96);
	//cout << "scratch 97" << endl;
	//data.alldata(data.scratch97);
	*/

	////////////////////////////////////
	///////////TEST DATA////////////////
	////////////////////////////////////

 	//TestData//HarmedTestData
	/*
	cout << "vial1_1" << endl;
	data.alldata(vial1_1);
	cout << "vial1_2" << endl;
	data.alldata(vial1_2);
	cout << "vial1_3" << endl;
	data.alldata(vial1_3);
	cout << "vial1_4" << endl;
	data.alldata(vial1_4);
	cout << "vial2_1" << endl;
	data.alldata(vial2_1);
	cout << "vial2_2" << endl;
	data.alldata(vial2_2);
	cout << "vial2_3" << endl;
	data.alldata(vial2_3);
	cout << "vial2_4" << endl;
	data.alldata(vial2_4);
	cout << "vial3_1" << endl;
	data.alldata(vial3_1);
	cout << "vial3_2" << endl;
	data.alldata(vial3_2);
	cout << "vial3_3" << endl;
	data.alldata(vial3_3);
	cout << "vial3_4" << endl;
	data.alldata(vial3_4);
	cout << "vial4_1" << endl;
	data.alldata(vial4_1);
	cout << "vial4_2" << endl;
	data.alldata(vial4_2);
	cout << "vial4_3" << endl;
	data.alldata(vial4_3);
	cout << "vial4_4" << endl;
	data.alldata(vial4_4);
	cout << "vial5_1" << endl;
	data.alldata(vial5_1);
	cout << "vial5_2" << endl;
	data.alldata(vial5_2);
	cout << "vial5_3" << endl;
	data.alldata(vial5_3);
	cout << "vial5_4" << endl;
	data.alldata(vial5_4);
	cout << "vial6_1" << endl;
	data.alldata(vial6_1);
	cout << "vial6_2" << endl;
	data.alldata(vial6_2);
	cout << "vial6_3" << endl;
	data.alldata(vial6_3);
	cout << "vial6_4" << endl;
	data.alldata(vial6_4);
	cout << "vial7_1" << endl;
	data.alldata(vial7_1);
	cout << "vial7_2" << endl;
	data.alldata(vial7_2);
	cout << "vial7_3" << endl;
	data.alldata(vial7_3);
	cout << "vial7_4" << endl;
	data.alldata(vial7_4);
	cout << "vial8_1" << endl;
	data.alldata(vial8_1);
	cout << "vial8_2" << endl;
	data.alldata(vial8_2);
	cout << "vial8_3" << endl;
	data.alldata(vial8_3);
	cout << "vial8_4" << endl;
	data.alldata(vial8_4);
	cout << "vial9_1" << endl;
	data.alldata(vial9_1);
	cout << "vial9_2" << endl;
	data.alldata(vial9_2);
	cout << "vial9_3" << endl;
	data.alldata(vial9_3);
	cout << "vial9_4" << endl;
	data.alldata(vial9_4);
	cout << "vial10_1" << endl;
	data.alldata(vial10_1);
	cout << "vial10_2" << endl;
	data.alldata(vial10_2);
	cout << "vial10_3" << endl;
	data.alldata(vial10_3);
	cout << "vial10_4" << endl;
	data.alldata(vial10_4);
	cout << "vial11_1" << endl;
	data.alldata(vial11_1);
	cout << "vial11_2" << endl;
	data.alldata(vial11_2);
	cout << "vial11_3" << endl;
	data.alldata(vial11_3);
	cout << "vial11_4" << endl;
	data.alldata(vial11_4);
	cout << "vial12_1" << endl;
	data.alldata(vial12_1);
	cout << "vial12_2" << endl;
	data.alldata(vial12_2);
	cout << "vial12_3" << endl;
	data.alldata(vial12_3);
	cout << "vial12_4" << endl;
	data.alldata(vial12_4);
	cout << "vial13_1" << endl;
	data.alldata(vial13_1);
	cout << "vial13_2" << endl;
	data.alldata(vial13_2);
	cout << "vial13_3" << endl;
	data.alldata(vial13_3);
	cout << "vial13_4" << endl;
	data.alldata(vial13_4);
	cout << "vial14_1" << endl;
	data.alldata(vial14_1);
	cout << "vial14_2" << endl;
	data.alldata(vial14_2);
	cout << "vial14_3" << endl;
	data.alldata(vial14_3);
	cout << "vial14_4" << endl;
	data.alldata(vial14_4);
	cout << "vial15_1" << endl;
	data.alldata(vial15_1);
	cout << "vial15_2" << endl;
	data.alldata(vial15_2);
	cout << "vial15_3" << endl;
	data.alldata(vial15_3);
	cout << "vial15_4" << endl;
	data.alldata(vial15_4);
			*/
	cout << "vial16_1" << endl;
	data.alldata(vial16_1);
	cout << "vial16_2" << endl;
	data.alldata(vial16_2);
	cout << "vial16_3" << endl;
	data.alldata(vial16_3);
	cout << "vial16_4" << endl;
	data.alldata(vial16_4);
	cout << "vial17_1" << endl;
	data.alldata(vial17_1);
	cout << "vial17_2" << endl;
	data.alldata(vial17_2);
	cout << "vial17_3" << endl;
	data.alldata(vial17_3);
	//cout << "vial17_4" << endl;
	//data.alldata(vial17_4);
	cout << "vial18_1" << endl;
	data.alldata(vial18_1);
	cout << "vial18_2" << endl;
	data.alldata(vial18_2);
	cout << "vial18_3" << endl;
	data.alldata(vial18_3);
	//cout << "vial18_4" << endl;
	//data.alldata(vial18_4);
	cout << "vial19_1" << endl;
	data.alldata(vial19_1);
	cout << "vial19_2" << endl;
	data.alldata(vial19_2);
	cout << "vial19_3" << endl;
	data.alldata(vial19_3);
	//cout << "vial19_4" << endl;
	//data.alldata(vial19_4);

	//TestData//GoodTestData
	cout << "goodtest1" << endl;
	data.alldata(goodtest1);
	cout << "goodtest2" << endl;
	data.alldata(goodtest2);
	cout << "goodtest3" << endl;
	data.alldata(goodtest3);
	cout << "goodtest4" << endl;
	data.alldata(goodtest4);
	cout << "goodtest5" << endl;
	data.alldata(goodtest5);
	cout << "goodtest6" << endl;
	data.alldata(goodtest6);
	cout << "goodtest7" << endl;
	data.alldata(goodtest7);
	cout << "goodtest8" << endl;
	data.alldata(goodtest8);
	cout << "goodtest9" << endl;
	data.alldata(goodtest9);
	cout << "goodtest10" << endl;
	data.alldata(goodtest10);
	cout << "goodtest11" << endl;
	data.alldata(goodtest11);
	cout << "goodtest12" << endl;
	data.alldata(goodtest12);
	cout << "goodtest13" << endl;
	data.alldata(goodtest13);
	cout << "goodtest14" << endl;
	data.alldata(goodtest14);
	cout << "goodtest15" << endl;
	data.alldata(goodtest15);
	cout << "goodtest16" << endl;
	data.alldata(goodtest16);
	cout << "goodtest17" << endl;
	data.alldata(goodtest17);
	cout << "goodtest18" << endl;
	data.alldata(goodtest18);
	cout << "goodtest19" << endl;
	data.alldata(goodtest19);
	cout << "goodtest20" << endl;
	data.alldata(goodtest20);
	cout << "goodtest21" << endl;
	data.alldata(goodtest21);
	cout << "goodtest22" << endl;
	data.alldata(goodtest22);
	cout << "goodtest23" << endl;
	data.alldata(goodtest23);
	cout << "goodtest24" << endl;
	data.alldata(goodtest24);
	cout << "goodtest25" << endl;
	data.alldata(goodtest25);
	cout << "goodtest26" << endl;
	data.alldata(goodtest26);
	cout << "goodtest27" << endl;
	data.alldata(goodtest27);
	cout << "goodtest28" << endl;
	data.alldata(goodtest28);
	cout << "goodtest29" << endl;
	data.alldata(goodtest29);
	cout << "goodtest30" << endl;
	data.alldata(goodtest30);
	cout << "goodtest31" << endl;
	data.alldata(goodtest31);
	cout << "goodtest32" << endl;
	data.alldata(goodtest32);
	cout << "goodtest33" << endl;
	data.alldata(goodtest33);
	cout << "goodtest34" << endl;
	data.alldata(goodtest34);
	cout << "goodtest35" << endl;
	data.alldata(goodtest35);
	cout << "goodtest36" << endl;
	data.alldata(goodtest36);
	cout << "goodtest37" << endl;
	data.alldata(goodtest37);
	cout << "goodtest38" << endl;
	data.alldata(goodtest38);
	cout << "goodtest39" << endl;
	data.alldata(goodtest39);
	cout << "goodtest40" << endl;
	data.alldata(goodtest40);
	cout << "goodtest41" << endl;
	data.alldata(goodtest41);
	cout << "goodtest42" << endl;
	data.alldata(goodtest42);
	cout << "goodtest43" << endl;
	data.alldata(goodtest43);
	cout << "goodtest44" << endl;
	data.alldata(goodtest44);
	cout << "goodtest45" << endl;
	data.alldata(goodtest45);
	cout << "goodtest46" << endl;
	data.alldata(goodtest46);
	cout << "goodtest47" << endl;
	data.alldata(goodtest47);
	cout << "goodtest48" << endl;
	data.alldata(goodtest48);
	cout << "goodtest49" << endl;
	data.alldata(goodtest49);
	cout << "goodtest50" << endl;
	data.alldata(goodtest50);
	
	
	/*
	cout << "test1" << endl;
	data.alldata(test1);
	cout << "test2" << endl;
	data.alldata(test2);
	cout << "test3" << endl;
	data.alldata(test3);
	cout << "test4" << endl;
	data.alldata(test4);
	cout << "test5" << endl;
	data.alldata(test5);
	cout << "test6" << endl;
	data.alldata(test6);
	cout << "test7" << endl;
	data.alldata(test7);
	cout << "test8" << endl;
	data.alldata(test8);
	cout << "test9" << endl;
	data.alldata(test9);
	*/
}
